/* Generated By:JavaCC: Do not edit this line. Assignment5Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Assignment5Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IGNORE = 1;
  /** RegularExpression Id. */
  int CHARACTER = 6;
  /** RegularExpression Id. */
  int RESERVED_WORD = 7;
  /** RegularExpression Id. */
  int SPECIAL_SYMBOL_TOKEN = 8;
  /** RegularExpression Id. */
  int IDENTIFIER = 9;
  /** RegularExpression Id. */
  int INTEGER_NUMBER = 10;
  /** RegularExpression Id. */
  int DECIMAL = 11;
  /** RegularExpression Id. */
  int OCTAL = 12;
  /** RegularExpression Id. */
  int HEXADECIMAL = 13;
  /** RegularExpression Id. */
  int LETTER = 14;
  /** RegularExpression Id. */
  int DIGIT = 15;
  /** RegularExpression Id. */
  int EXPONENT = 16;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int MULTI_LINE_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<IGNORE>",
    "<token of kind 2>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 5>",
    "<CHARACTER>",
    "<RESERVED_WORD>",
    "<SPECIAL_SYMBOL_TOKEN>",
    "<IDENTIFIER>",
    "<INTEGER_NUMBER>",
    "<DECIMAL>",
    "<OCTAL>",
    "<HEXADECIMAL>",
    "<LETTER>",
    "<DIGIT>",
    "<EXPONENT>",
  };

}
