/* Generated By:JavaCC: Do not edit this line. Assignment5Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Assignment5Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IGNORE = 1;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 2;
  /** RegularExpression Id. */
  int CHARACTER = 3;
  /** RegularExpression Id. */
  int RESERVED_WORD = 4;
  /** RegularExpression Id. */
  int SPECIAL_SYMBOL_TOKEN = 5;
  /** RegularExpression Id. */
  int IDENTIFIER = 6;
  /** RegularExpression Id. */
  int INTEGER_NUMBER = 7;
  /** RegularExpression Id. */
  int DECIMAL = 8;
  /** RegularExpression Id. */
  int OCTAL = 9;
  /** RegularExpression Id. */
  int HEXADECIMAL = 10;
  /** RegularExpression Id. */
  int LETTER = 11;
  /** RegularExpression Id. */
  int DIGIT = 12;
  /** RegularExpression Id. */
  int EXPONENT = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<IGNORE>",
    "\"//( )*(<LETTER>)*\"",
    "<CHARACTER>",
    "<RESERVED_WORD>",
    "<SPECIAL_SYMBOL_TOKEN>",
    "<IDENTIFIER>",
    "<INTEGER_NUMBER>",
    "<DECIMAL>",
    "<OCTAL>",
    "<HEXADECIMAL>",
    "<LETTER>",
    "<DIGIT>",
    "<EXPONENT>",
  };

}
