/* Generated By:JJTree&JavaCC: Do not edit this line. PclParserConstants.java */
package wci.frontend;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PclParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMENT = 5;
  /** RegularExpression Id. */
  int BEGIN = 6;
  /** RegularExpression Id. */
  int END = 7;
  /** RegularExpression Id. */
  int PROGRAM = 8;
  /** RegularExpression Id. */
  int VAR = 9;
  /** RegularExpression Id. */
  int COLON = 10;
  /** RegularExpression Id. */
  int COLON_EQUALS = 11;
  /** RegularExpression Id. */
  int COMMA = 12;
  /** RegularExpression Id. */
  int DOT = 13;
  /** RegularExpression Id. */
  int SEMICOLON = 14;
  /** RegularExpression Id. */
  int PLUS = 15;
  /** RegularExpression Id. */
  int MINUS = 16;
  /** RegularExpression Id. */
  int STAR = 17;
  /** RegularExpression Id. */
  int SLASH = 18;
  /** RegularExpression Id. */
  int QUOTE = 19;
  /** RegularExpression Id. */
  int IDENTIFIER = 20;
  /** RegularExpression Id. */
  int STRING = 21;
  /** RegularExpression Id. */
  int INTEGER = 22;
  /** RegularExpression Id. */
  int REAL = 23;
  /** RegularExpression Id. */
  int LETTER = 24;
  /** RegularExpression Id. */
  int DIGIT = 25;
  /** RegularExpression Id. */
  int SIGN = 26;
  /** RegularExpression Id. */
  int UNSIGNED_NUMBER = 27;
  /** RegularExpression Id. */
  int WHOLE = 28;
  /** RegularExpression Id. */
  int FRACTION = 29;
  /** RegularExpression Id. */
  int EXPONENT = 30;
  /** RegularExpression Id. */
  int ERROR = 31;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<COMMENT>",
    "\"BEGIN\"",
    "\"END\"",
    "\"PROGRAM\"",
    "\"VAR\"",
    "\":\"",
    "\":=\"",
    "\",\"",
    "\".\"",
    "\";\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"\\\'\"",
    "<IDENTIFIER>",
    "<STRING>",
    "<INTEGER>",
    "<REAL>",
    "<LETTER>",
    "<DIGIT>",
    "<SIGN>",
    "<UNSIGNED_NUMBER>",
    "<WHOLE>",
    "<FRACTION>",
    "<EXPONENT>",
    "<ERROR>",
  };

}
