/* Generated By:JavaCC: Do not edit this line. PclParserTreeConstants.java Version 5.0 */
package wci.frontend;

public interface PclParserTreeConstants
{
  public int JJTVOID = 0;
  public int JJTCOMPOUNDSTATEMENT = 1;
  public int JJTASSIGNMENTSTATEMENT = 2;
  public int JJTADD = 3;
  public int JJTSUBTRACT = 4;
  public int JJTMULTIPLY = 5;
  public int JJTDIVIDE = 6;
  public int JJTVARIABLE = 7;
  public int JJTINTEGERCONSTANT = 8;
  public int JJTREALCONSTANT = 9;


  public String[] jjtNodeName = {
    "void",
    "compoundStatement",
    "assignmentStatement",
    "add",
    "subtract",
    "multiply",
    "divide",
    "variable",
    "integerConstant",
    "realConstant",
  };
}
/* JavaCC - OriginalChecksum=ec00b0c766cfea3c7851e548fb34193a (do not edit this line) */
