/* Generated By:JavaCC: Do not edit this line. GoParserTreeConstants.java Version 5.0 */
package wci.frontend;

public interface GoParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTSTATEMENT = 1;
  public int JJTSTATEMENTLIST = 2;
  public int JJTBLOCK = 3;
  public int JJTIFSTATEMENT = 4;
  public int JJTSWITCHSTATEMENT = 5;
  public int JJTSWITCHBLOCK = 6;
  public int JJTCASEGROUP = 7;
  public int JJTASSIGNMENTSTATEMENT = 8;
  public int JJTINCORDEC = 9;
  public int JJTFORSTATEMENT = 10;
  public int JJTFORCLAUSE = 11;
  public int JJTRANGECLAUSE = 12;
  public int JJTOPERAND = 13;
  public int JJTEXPRESSION = 14;
  public int JJTEXPRESSIONLIST = 15;
  public int JJTVOID = 16;


  public String[] jjtNodeName = {
    "start",
    "statement",
    "statementList",
    "block",
    "ifStatement",
    "switchStatement",
    "switchBlock",
    "caseGroup",
    "assignmentStatement",
    "incOrDec",
    "forStatement",
    "forClause",
    "rangeClause",
    "operand",
    "expression",
    "expressionList",
    "void",
  };
}
/* JavaCC - OriginalChecksum=08c134d861e16098f7cad6bb3650b5b5 (do not edit this line) */
