/* Generated By:JavaCC: Do not edit this line. GoParserTreeConstants.java Version 5.0 */
package wci.frontend;

public interface GoParserTreeConstants
{
  public int JJTVOID = 0;
  public int JJTASSIGNMENTSTATEMENT = 1;


  public String[] jjtNodeName = {
    "void",
    "assignmentStatement",
  };
}
/* JavaCC - OriginalChecksum=aca06f41afc9b1811a89e3889c0e2d38 (do not edit this line) */
