/* Generated By:JavaCC: Do not edit this line. GoParserTreeConstants.java Version 5.0 */
package wci.frontend;

public interface GoParserTreeConstants
{
  public int JJTVOID = 0;
  public int JJTBLOCK = 1;


  public String[] jjtNodeName = {
    "void",
    "block",
  };
}
/* JavaCC - OriginalChecksum=e2cfa58bb3a7b2de06919c018b68643d (do not edit this line) */
