/* Generated By:JavaCC: Do not edit this line. GoParserVisitor.java Version 5.0 */
package wci.frontend;

public interface GoParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTassignmentStatement node, Object data);
}
/* JavaCC - OriginalChecksum=fc22a20b3d5d996be1203812993b27c3 (do not edit this line) */
