/* Generated By:JavaCC: Do not edit this line. GoParserVisitor.java Version 5.0 */
package wci.frontend;

public interface GoParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTblock node, Object data);
}
/* JavaCC - OriginalChecksum=7a8e9d1f8b1842d88417e89254dbd1fa (do not edit this line) */
